### ISSUE TITLE
Server connection issue

### ISSUE THREAD

**Issue by carijulian** [flathub/com.tutanota.Tutanota#191]
![screenshot_20240621_165504](https://github.com/flathub/com.tutanota.Tutanota/assets/135532916/e034d663-7a91-4157-873e-b926092b51f4)

Log:
```bash
$ flatpak run com.tutanota.Tutanota 
[2:0621/165651.083788:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
the monkey has been patched pid: 2
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)
[2:0621/165651.997138:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0621/165651.997350:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
version:   230.240603.0
resolving key... tutanota-vault
config up to date
[2024-06-21T09:56:52.511Z] using safeStorage with backend gnome_libsecret
[DesktopMain] getting dictionaries from: https://app.tuta.com/desktop//dictionaries/
[2024-06-21T09:56:52.530Z] Create tray:true
[SSEFacade] last missed notification check: { lastMissedNotificationCheckTime: null }
[ApplicationWindow] webAssetsPath:  /app/lib/tutanota/resources/app.asar
default mailto handler: false
Webapp ready
[2024-06-21T09:56:52.916Z] [ElectronUpdater] DEBUG: no update info on disk, disabling updater.
[SSEFacade] No SSE info
[DesktopMain] spellcheck-dictionary-download-begin en-US
desktop file exists, checking version...
[2:0621/165654.560688:ERROR:nss_util.cc(239)] Error initializing NSS with a persistent database (sql:/home/julian/.pki/nssdb): NSS error code: -8126
[DesktopMain] spellcheck-dictionary-download-failure en-US
[ProtocolProxy] error for GET https://app.tuta.com/rest/sys/saltservice:
[ProtocolProxy] TypeError: fetch failed
    at Jp (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:10:1472)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:10:30651
    at async AsyncFunction.<anonymous> (node:electron/js2c/browser_init:2:51595) {
  [cause]: AggregateError
      at internalConnectMultiple (node:net:1114:18)
      at internalConnectMultiple (node:net:1177:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ETIMEDOUT',
    [errors]: [ [Error], [Error] ]
  }
}
[ProtocolProxy] {"name":"TypeError","message":"fetch failed","stack":"TypeError: fetch failed\n    at Jp (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:10:1472)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:10:30651\n    at async AsyncFunction.<anonymous> (node:electron/js2c/browser_init:2:51595)"}
[ProtocolProxy] failed after 376ms
```

**Comment by charlag** [comment]
It looks like a general connection issue/timeout. Please contact support if the issue persists.
